make: main.cpp glad.c
	g++ -I /home/obliterator/Euclid_Engine/src main.cpp glad.c -o bin/triangle -Wall -lGL -lGLU -lglfw3 -lX11 -lXxf86vm -lXrandr -lpthread -lXi -ldl -lXinerama -lXcursor
# use this to run cd /home/obliterator/Euclid_Engine/src && make && bin/triangle
